package Interfaz;

import Estructuras.Arbol;
import Estructuras.BinarySearchTree;
import Estructuras.Lugar;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import maps.java.Places;
import maps.java.ShowMaps;
import maps.java.StaticMaps;

/**
 *
 * @author Maria Jose M
 */
public class PlacesFrame extends javax.swing.JFrame {

      DefaultListModel modelo = new DefaultListModel(); 
//      Arbol arbolbinario = new Arbol();
    
    
 
    private String referencePlace;
    private Places ObjPlaces=new Places();
    private String[][] datosReview;
    private ArrayList<String> fotosReferencia;
    private ShowMaps ObjShowMaps=new ShowMaps();
    private StaticMaps ObjStaticMaps=new StaticMaps();
    
    private Icon cargarImagen(String url) throws IOException{
        Image imagen;
        imagen=ImageIO.read(new URL(url));
        imagen=imagen.getScaledInstance(35,35,Image.SCALE_FAST);
        ImageIcon imgIcon=new ImageIcon(imagen);
        Icon iconImage=(Icon)imgIcon;
        return iconImage;
    }
    
     public void AgregarFavoritos (){
        jListFavoritos.setModel(modelo);
        String favorito = JText_DP_Nombre.getText();
        modelo.addElement (favorito);
    
}

            
    private void cargarInfo() throws UnsupportedEncodingException, MalformedURLException, IOException{
        String[] datos=ObjPlaces.getPlacesDetails(this.referencePlace);
        this.JText_DP_Nombre.setText(datos[0]);
        this.JText_DP_Vecindad.setText(datos[1]);
        this.JText_DP_Telefono.setText(datos[2]);
        this.JText_DP_Direccion.setText(datos[3]);
        this.JText_DP_URLGoogle.setText(datos[4]);
        this.JText_DP_Puntuacion.setText(datos[5]);
        this.JText_DP_Web.setText(datos[7]);
        this.JLabel_DP_NombrePr.setText(datos[0]);
        this.JLabel_DP_Icono.setText("");
        this.JLabel_DP_Icono.setIcon(cargarImagen(datos[6]));
         this.jLabel_DP_MapaEst.setText("");
        Image mapaEst=ObjStaticMaps.getStaticMap(datos[3],15,new Dimension(480,80),1, StaticMaps.Format.jpg, StaticMaps.Maptype.roadmap);
        ImageIcon imgIcon=new ImageIcon(mapaEst);
        Icon iconImage=(Icon)imgIcon;   
        this.jLabel_DP_MapaEst.setIcon(iconImage);
        
    }
    
    
 
            
    public PlacesFrame(String _referencePlace) throws UnsupportedEncodingException {
        initComponents();
        referencePlace=_referencePlace;
        try {
          cargarInfo(); 
         
        } catch (Exception e) {
        }
    }

    private PlacesFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JText_DP_Nombre = new javax.swing.JTextField();
        JText_DP_Vecindad = new javax.swing.JTextField();
        JText_DP_Direccion = new javax.swing.JTextField();
        JText_DP_Telefono = new javax.swing.JTextField();
        JText_DP_URLGoogle = new javax.swing.JTextField();
        JText_DP_Puntuacion = new javax.swing.JTextField();
        JText_DP_Web = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JLabel_DP_NombrePr = new javax.swing.JLabel();
        JLabel_DP_Icono = new javax.swing.JLabel();
        jButtonAgregarFav = new javax.swing.JButton();
        jLabel_DP_MapaEst = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListFavoritos = new javax.swing.JList<>();
        jButtonEliminarFav = new javax.swing.JButton();

        setTitle("Detalles Place");
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBackground(new java.awt.Color(7, 113, 142));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vecindad:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dirección:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("URL Google+:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Puntuación (/5):");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Página web:");

        JText_DP_Nombre.setEditable(false);

        JText_DP_Vecindad.setEditable(false);

        JText_DP_Direccion.setEditable(false);

        JText_DP_Telefono.setEditable(false);

        JText_DP_URLGoogle.setEditable(false);

        JText_DP_Puntuacion.setEditable(false);

        JText_DP_Web.setEditable(false);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Abrir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(7, 113, 142));

        JLabel_DP_NombrePr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel_DP_NombrePr.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_DP_NombrePr.setText("Nombre");

        JLabel_DP_Icono.setText("Icono");

        jButtonAgregarFav.setBackground(new java.awt.Color(255, 153, 0));
        jButtonAgregarFav.setText("Agregar a Favorito");
        jButtonAgregarFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_DP_NombrePr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabel_DP_Icono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregarFav)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_DP_NombrePr)
                    .addComponent(jButtonAgregarFav)))
            .addComponent(JLabel_DP_Icono)
        );

        jLabel_DP_MapaEst.setText("jLabel11");
        jLabel_DP_MapaEst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JText_DP_Nombre)
                            .addComponent(JText_DP_Vecindad)
                            .addComponent(JText_DP_Telefono)
                            .addComponent(JText_DP_Puntuacion)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JText_DP_URLGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JText_DP_Web)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(JText_DP_Direccion)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_DP_MapaEst, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JText_DP_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JText_DP_Vecindad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JText_DP_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JText_DP_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JText_DP_URLGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JText_DP_Puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JText_DP_Web, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel_DP_MapaEst, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos ", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setViewportView(jListFavoritos);

        jButtonEliminarFav.setBackground(new java.awt.Color(255, 153, 0));
        jButtonEliminarFav.setText("Eliminar Favorito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonEliminarFav))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButtonEliminarFav)
                .addGap(86, 86, 86))
        );

        jTabbedPane1.addTab("Favoritos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Datos place");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void abrirWeb(String url) throws URISyntaxException, IOException{
        Desktop.getDesktop().browse(new URI(url));
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!JText_DP_Web.getText().isEmpty() && !"NO DATA".equals(JText_DP_Web.getText())){
            try {
                abrirWeb(JText_DP_Web.getText());
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!JText_DP_URLGoogle.getText().isEmpty() && !"NO DATA".equals(JText_DP_URLGoogle.getText())){
            try {
                abrirWeb(JText_DP_URLGoogle.getText());
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButtonAgregarFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFavActionPerformed

        AgregarFavoritos();
//       Lugar nuevoLugar = new Lugar();
//       nuevoLugar.setDirección(JText_DP_Nombre.getText());
//        System.out.println(JText_DP_Nombre.getText());
//        arbolbinario.insertar(nuevoLugar);
//        arbolbinario.inorden();

     
      
        // agregar el nombre a un jtxt en la pagina principal
//        PaginaPrincipal.jTextFieldAgregarFavArbol.setText(JText_DP_Nombre.getText());


    }//GEN-LAST:event_jButtonAgregarFavActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacesFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_DP_Icono;
    private javax.swing.JLabel JLabel_DP_NombrePr;
    private javax.swing.JTextField JText_DP_Direccion;
    private javax.swing.JTextField JText_DP_Nombre;
    private javax.swing.JTextField JText_DP_Puntuacion;
    private javax.swing.JTextField JText_DP_Telefono;
    private javax.swing.JTextField JText_DP_URLGoogle;
    private javax.swing.JTextField JText_DP_Vecindad;
    private javax.swing.JTextField JText_DP_Web;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgregarFav;
    private javax.swing.JButton jButtonEliminarFav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_DP_MapaEst;
    private javax.swing.JList<String> jListFavoritos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
